#!/usr/bin/env bash
# Copyright 2023 GlitchyByte
# SPDX-License-Identifier: MIT

# checkfix v1.0.0

# [Setup]
set -u
set -e
# Capture caller directory and script directory.
readonly calling_dir="${PWD}"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"
. ./_gcolors

if [ "$#" -eq 0 ]; then
  readonly scan_dir="."
else
  readonly scan_dir="$1"
fi
readonly cc_text="$(color256 2 2 2)"
readonly cc_dir="$(color256 5 5 5)"
readonly cc_line="$(color256 5 3 0)"

# [Main]
echo "${cc_text}Scanning: ${cc_dir}${scan_dir}${c_reset}"

egrep -rnI --exclude-dir=".*" "// +TODO:|// +FIXME:" "${scan_dir}" | \
  awk -v cc_path="${cc_text}" -v cc_line="${cc_line}" -v c_reset="${c_reset}" -F: \
    '{print cc_path $1":"$2; sub(/^ +/,"",$3); printf "%s%s",cc_line,$3; for (i = 4; i <= NF; i++) printf "%s",$i; print c_reset}'

# [Teardown]
cd "${calling_dir}"
